version: 2
jobs:
  build:
    docker:
      - image: ruby:2.3
      - image: postgres:9.4.1
        environment:
          POSTGRES_USER: root

    working_directory: /home/ubuntu/cci-demo-rails
    steps:
      - checkout
      - run:
          name: Install System Dependencies
          command: apt-get update -qq && apt-get install -y build-essential nodejs
      - run:
          name: Install Ruby Dependencies
          command: bundle install
      - run:
          name: Create DB
          command: bundle exec rake db:create db:schema:load --trace
      - run:
          name: DB Migrations
          command: bundle exec rake db:migrate
      - run:
          name: Run Tests
          command: bundle exec rake test
