default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: root
  password: 
  host: db

development:
  <<: *default
  database: dev_db

test:
  <<: *default
  database: test_db

production:
  <<: *default
  database: prod_db
